/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedRidesRouteImport } from './routes/_authenticated.rides'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated.drive.index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated.profile.index'
import { Route as AuthenticatedProfileDevicesRouteImport } from './routes/_authenticated.profile.devices'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated.profile.edit'
import { Route as AuthenticatedProfileEmergencyContactsRouteImport } from './routes/_authenticated.profile.emergency-contacts'
import { Route as AuthenticatedProfileNotificationsRouteImport } from './routes/_authenticated.profile.notifications'
import { Route as AuthenticatedProfilePrivacyDataRouteImport } from './routes/_authenticated.profile.privacy-data'
import { Route as AuthenticatedProfileSavedPlacesRouteImport } from './routes/_authenticated.profile.saved-places'
import { Route as AuthenticatedRideBookingIdRouteImport } from './routes/_authenticated.ride.$bookingId'
import { Route as AuthenticatedRideNewRouteImport } from './routes/_authenticated.ride.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRidesRoute = AuthenticatedRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileDevicesRoute =
  AuthenticatedProfileDevicesRouteImport.update({
    id: '/profile/devices',
    path: '/profile/devices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileEmergencyContactsRoute =
  AuthenticatedProfileEmergencyContactsRouteImport.update({
    id: '/profile/emergency-contacts',
    path: '/profile/emergency-contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileNotificationsRoute =
  AuthenticatedProfileNotificationsRouteImport.update({
    id: '/profile/notifications',
    path: '/profile/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilePrivacyDataRoute =
  AuthenticatedProfilePrivacyDataRouteImport.update({
    id: '/profile/privacy-data',
    path: '/profile/privacy-data',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileSavedPlacesRoute =
  AuthenticatedProfileSavedPlacesRouteImport.update({
    id: '/profile/saved-places',
    path: '/profile/saved-places',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRideBookingIdRoute =
  AuthenticatedRideBookingIdRouteImport.update({
    id: '/ride/$bookingId',
    path: '/ride/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRideNewRoute = AuthenticatedRideNewRouteImport.update({
  id: '/ride/new',
  path: '/ride/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/rides': typeof AuthenticatedRidesRoute
  '/profile/devices': typeof AuthenticatedProfileDevicesRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/emergency-contacts': typeof AuthenticatedProfileEmergencyContactsRoute
  '/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/profile/privacy-data': typeof AuthenticatedProfilePrivacyDataRoute
  '/profile/saved-places': typeof AuthenticatedProfileSavedPlacesRoute
  '/ride/$bookingId': typeof AuthenticatedRideBookingIdRoute
  '/ride/new': typeof AuthenticatedRideNewRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/rides': typeof AuthenticatedRidesRoute
  '/profile/devices': typeof AuthenticatedProfileDevicesRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/emergency-contacts': typeof AuthenticatedProfileEmergencyContactsRoute
  '/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/profile/privacy-data': typeof AuthenticatedProfilePrivacyDataRoute
  '/profile/saved-places': typeof AuthenticatedProfileSavedPlacesRoute
  '/ride/$bookingId': typeof AuthenticatedRideBookingIdRoute
  '/ride/new': typeof AuthenticatedRideNewRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/rides': typeof AuthenticatedRidesRoute
  '/_authenticated/profile/devices': typeof AuthenticatedProfileDevicesRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/emergency-contacts': typeof AuthenticatedProfileEmergencyContactsRoute
  '/_authenticated/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/_authenticated/profile/privacy-data': typeof AuthenticatedProfilePrivacyDataRoute
  '/_authenticated/profile/saved-places': typeof AuthenticatedProfileSavedPlacesRoute
  '/_authenticated/ride/$bookingId': typeof AuthenticatedRideBookingIdRoute
  '/_authenticated/ride/new': typeof AuthenticatedRideNewRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/home'
    | '/rides'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/emergency-contacts'
    | '/profile/notifications'
    | '/profile/privacy-data'
    | '/profile/saved-places'
    | '/ride/$bookingId'
    | '/ride/new'
    | '/drive/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/home'
    | '/rides'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/emergency-contacts'
    | '/profile/notifications'
    | '/profile/privacy-data'
    | '/profile/saved-places'
    | '/ride/$bookingId'
    | '/ride/new'
    | '/drive'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/home'
    | '/_authenticated/rides'
    | '/_authenticated/profile/devices'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/emergency-contacts'
    | '/_authenticated/profile/notifications'
    | '/_authenticated/profile/privacy-data'
    | '/_authenticated/profile/saved-places'
    | '/_authenticated/ride/$bookingId'
    | '/_authenticated/ride/new'
    | '/_authenticated/drive/'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rides': {
      id: '/_authenticated/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof AuthenticatedRidesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/devices': {
      id: '/_authenticated/profile/devices'
      path: '/profile/devices'
      fullPath: '/profile/devices'
      preLoaderRoute: typeof AuthenticatedProfileDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/emergency-contacts': {
      id: '/_authenticated/profile/emergency-contacts'
      path: '/profile/emergency-contacts'
      fullPath: '/profile/emergency-contacts'
      preLoaderRoute: typeof AuthenticatedProfileEmergencyContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/notifications': {
      id: '/_authenticated/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AuthenticatedProfileNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/privacy-data': {
      id: '/_authenticated/profile/privacy-data'
      path: '/profile/privacy-data'
      fullPath: '/profile/privacy-data'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/saved-places': {
      id: '/_authenticated/profile/saved-places'
      path: '/profile/saved-places'
      fullPath: '/profile/saved-places'
      preLoaderRoute: typeof AuthenticatedProfileSavedPlacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ride/$bookingId': {
      id: '/_authenticated/ride/$bookingId'
      path: '/ride/$bookingId'
      fullPath: '/ride/$bookingId'
      preLoaderRoute: typeof AuthenticatedRideBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ride/new': {
      id: '/_authenticated/ride/new'
      path: '/ride/new'
      fullPath: '/ride/new'
      preLoaderRoute: typeof AuthenticatedRideNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedRidesRoute: typeof AuthenticatedRidesRoute
  AuthenticatedProfileDevicesRoute: typeof AuthenticatedProfileDevicesRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileEmergencyContactsRoute: typeof AuthenticatedProfileEmergencyContactsRoute
  AuthenticatedProfileNotificationsRoute: typeof AuthenticatedProfileNotificationsRoute
  AuthenticatedProfilePrivacyDataRoute: typeof AuthenticatedProfilePrivacyDataRoute
  AuthenticatedProfileSavedPlacesRoute: typeof AuthenticatedProfileSavedPlacesRoute
  AuthenticatedRideBookingIdRoute: typeof AuthenticatedRideBookingIdRoute
  AuthenticatedRideNewRoute: typeof AuthenticatedRideNewRoute
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedRidesRoute: AuthenticatedRidesRoute,
  AuthenticatedProfileDevicesRoute: AuthenticatedProfileDevicesRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileEmergencyContactsRoute:
    AuthenticatedProfileEmergencyContactsRoute,
  AuthenticatedProfileNotificationsRoute:
    AuthenticatedProfileNotificationsRoute,
  AuthenticatedProfilePrivacyDataRoute: AuthenticatedProfilePrivacyDataRoute,
  AuthenticatedProfileSavedPlacesRoute: AuthenticatedProfileSavedPlacesRoute,
  AuthenticatedRideBookingIdRoute: AuthenticatedRideBookingIdRoute,
  AuthenticatedRideNewRoute: AuthenticatedRideNewRoute,
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
