/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated.profile.index'
import { Route as AuthenticatedProfileDevicesRouteImport } from './routes/_authenticated.profile.devices'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated.profile.edit'
import { Route as AuthenticatedProfileEmergencyContactsRouteImport } from './routes/_authenticated.profile.emergency-contacts'
import { Route as AuthenticatedProfileSavedPlacesRouteImport } from './routes/_authenticated.profile.saved-places'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileDevicesRoute =
  AuthenticatedProfileDevicesRouteImport.update({
    id: '/profile/devices',
    path: '/profile/devices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileEmergencyContactsRoute =
  AuthenticatedProfileEmergencyContactsRouteImport.update({
    id: '/profile/emergency-contacts',
    path: '/profile/emergency-contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileSavedPlacesRoute =
  AuthenticatedProfileSavedPlacesRouteImport.update({
    id: '/profile/saved-places',
    path: '/profile/saved-places',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile/devices': typeof AuthenticatedProfileDevicesRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/emergency-contacts': typeof AuthenticatedProfileEmergencyContactsRoute
  '/profile/saved-places': typeof AuthenticatedProfileSavedPlacesRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile/devices': typeof AuthenticatedProfileDevicesRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/emergency-contacts': typeof AuthenticatedProfileEmergencyContactsRoute
  '/profile/saved-places': typeof AuthenticatedProfileSavedPlacesRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile/devices': typeof AuthenticatedProfileDevicesRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/emergency-contacts': typeof AuthenticatedProfileEmergencyContactsRoute
  '/_authenticated/profile/saved-places': typeof AuthenticatedProfileSavedPlacesRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/emergency-contacts'
    | '/profile/saved-places'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/emergency-contacts'
    | '/profile/saved-places'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/profile/devices'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/emergency-contacts'
    | '/_authenticated/profile/saved-places'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/devices': {
      id: '/_authenticated/profile/devices'
      path: '/profile/devices'
      fullPath: '/profile/devices'
      preLoaderRoute: typeof AuthenticatedProfileDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/emergency-contacts': {
      id: '/_authenticated/profile/emergency-contacts'
      path: '/profile/emergency-contacts'
      fullPath: '/profile/emergency-contacts'
      preLoaderRoute: typeof AuthenticatedProfileEmergencyContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/saved-places': {
      id: '/_authenticated/profile/saved-places'
      path: '/profile/saved-places'
      fullPath: '/profile/saved-places'
      preLoaderRoute: typeof AuthenticatedProfileSavedPlacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileDevicesRoute: typeof AuthenticatedProfileDevicesRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileEmergencyContactsRoute: typeof AuthenticatedProfileEmergencyContactsRoute
  AuthenticatedProfileSavedPlacesRoute: typeof AuthenticatedProfileSavedPlacesRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileDevicesRoute: AuthenticatedProfileDevicesRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileEmergencyContactsRoute:
    AuthenticatedProfileEmergencyContactsRoute,
  AuthenticatedProfileSavedPlacesRoute: AuthenticatedProfileSavedPlacesRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
